### ISSUE TITLE
details about other python library

### ISSUE THREAD

**Issue by eric246** [nikvaessen/w2v2-speaker#6]
Thanks for your code. I'm just getting started with python. There are always some errors when I configure the environment. Can you list the versions of the pytorch-lightning, torchmetric, and etc. python libraries you use?

**Comment by nikvaessen** [comment]
from https://github.com/nikvaessen/w2v2-speaker/blob/master/pyproject.toml
pytorch-lightning = "1.4.5"

from https://github.com/nikvaessen/w2v2-speaker/blob/master/requirements/requirements_cuda111.txt:
torch==1.8.1+cu111
torchvision==0.9.1+cu111
torchaudio==0.8.1

**Comment by eric246** [comment]
Oh, I know. Thanks Nik.
