### ISSUE TITLE
requirement.txt 

### ISSUE THREAD

**Issue by Arthurwyf** [nikvaessen/w2v2-speaker#9]
Could you please release the version of the packages you use? Not just the torch version but the other packages version

**Comment by nikvaessen** [comment]
see https://github.com/nikvaessen/w2v2-speaker/blob/master/pyproject.toml, which are installed with `poetry`. See https://github.com/nikvaessen/w2v2-speaker#installing-dependencies

**Comment by Arthurwyf** [comment]
Thanks!
It does a lot of help. 
I am bothered by this all night. 
Thank you for your fast and helpful reply.
Love from China
